### h5py简单介绍
**h5py文件是存放两类对象的容器，数据集(dataset)和组(group)，dataset类似数组类的数据集合，和numpy的数组差不多。group是像文件夹一样的容器，它好比python中的字典，有键(key)和值(value)。group中可以存放dataset或者其他的group。”键”就是组成员的名称，”值”就是组成员对象本身(组或者数据集)，下面来看下如何创建组和数据集。**


**1. 创建一个h5py文件**

In [ ]:
import h5py
import numpy as np

#要是读取文件的话，就把w换成r
f=h5py.File("myh5py.hdf5","w")

**2. 创建dataset数据集**

In [13]:

#要是读取文件的话，就把w换成r
with h5py.File("myh5py.hdf5","w") as f:
    #deset1是数据集的name，（20,）代表数据集的shape，i代表的是数据集的元素类型
    d1=f.create_dataset("dset1", (20,), 'i')
    for key in f.keys():
        print(key)
        print(f[key].name)
        print(f[key].shape)
        print(f[key].value)

dset1
/dset1
(20,)
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [16]:
with h5py.File("myh5py.hdf5","w") as f:

    d1=f.create_dataset("dset1",(20,),'i')
    #赋值
    d1[...]=np.arange(20)
    #或者我们可以直接按照下面的方式创建数据集并赋值
    f["dset2"]=np.arange(15)

    for key in f.keys():
        print(f[key].name)
        print(f[key].value)

/dset1
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
/dset2
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
