In [6]:
# 导入
import numpy as np

In [14]:
# 生成数组

a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

- ndarray.ndim

数组轴的个数，在python的世界中，轴的个数被称作秩

- ndarray.shape

数组的维度。这是一个指示数组在每个维度上大小的整数元组。例如一个n排m列的矩阵，它的shape属性将是(2,3),这个元组的长度显然是秩，即维度或者ndim属性

- ndarray.size

数组元素的总个数，等于shape属性中元组元素的乘积。

- ndarray.dtype

一个用来描述数组中元素类型的对象，可以通过创造或指定dtype使用标准Python类型。另外NumPy提供它自己的数据类型。

- ndarray.itemsize

数组中每个元素的字节大小。例如，一个元素类型为float64的数组itemsiz属性值为8(=64/8),又如，一个元素类型为complex32的数组item属性为4(=32/8).

- ndarray.data

包含实际数组元素的缓冲区，通常我们不需要使用这个属性，因为我们总是通过索引来使用数组中的元素。

In [25]:
# 数组轴的个数，在python的世界中，轴的个数被称作秩（非数学中的秩）
print (a.ndim,',',a.shape)

2 , (3, 5)


In [43]:
# 修改数组的值
b = np.array([
    [1,2,3],
    [7,8,9]
])
b[0][1] = 1
b

array([[1, 1, 3],
       [7, 8, 9]])

# 基本运算

- ### 矩阵对应元素乘法

In [57]:
# 矩阵对应相乘
A = array( [
    [1,1],
    [2,1]
])
B = array([
    [2,0],
    [3,4]
])
A*B                        # 矩阵对应元素相乘


array([[2, 0],
       [6, 4]])

- ### 矩阵数学乘法

In [56]:
dot(A,B)                    # 数学意义上的乘法

array([[5, 4],
       [7, 4]])

In [65]:
C = dot(A,B)
C.T

array([[5, 7],
       [4, 4]])