In [1]:
import tensorflow as tf

C:\Users\Albert\Anaconda3\envs\env_ai\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


TensorFlow打印tensor值：
tensorflow提供输出中间值方法方便debug。 
> 这个函数就是tf.Print。

>tf.Print( input_, data, message=None, first_n=None, summarize=None, name=None )

参数: 
- input_:    通过此op的一个tensor. 
- data:     当此op被计算之后打印输出的tensor list。 
- message:   错误消息的前缀，是一个string。 
- first_n:   只记录first_n次. 总是记录负数;这是个缺省. 
- summarize:  对每个tensor只打印的条目数量。如果是None，对于每个输入tensor只打印3个元素。 
- name:     op的名字.

返回值: 
- 和input_相同的tensor.


In [192]:
# Example
def show(x):
    x=tf.Print(x,[x,x.shape,'any thing i want'],message='Debug message:',summarize=100)
    init = tf.global_variables_initializer()

    with tf.Session() as sess:
        sess.run(init)
        print("------------")
        print(x)
        print(sess.run(x))

### 创建常量tensor
```
tf.constant(
    value,
    dtype=None,
    shape=None,
    name='Const',
    verify_shape=False
)
```
Args:
- value: A constant value (or list) of output type dtype.
- dtype: The type of the elements of the resulting tensor.
- shape: Optional dimensions of resulting tensor.
- name: Optional name for the tensor.
- verify_shape: Boolean that enables verification of a shape of values.

Returns:
- A Constant Tensor.

### 1.常量tensor 

In [185]:
# 填充0
# tf.zeros(
#     shape,
#     dtype=tf.float32,
#     name=None
# )
show(tf.zeros([2, 3]))

# 填充1
# tf.ones(
#     shape,
#     dtype=tf.float32,
#     name=None
# )
show(tf.ones([1, 3]))

# 填充指定值
show(tf.fill([2, 4], 8))

#创建一个自定义的常量
show(tf.constant([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]))

# 等价于fill
show(tf.constant(8, tf.float32, [2,4]))

------------
Tensor("Print_70:0", shape=(2, 3), dtype=float32)
[[0. 0. 0.]
 [0. 0. 0.]]
------------
Tensor("Print_71:0", shape=(1, 3), dtype=float32)
[[1. 1. 1.]]
------------
Tensor("Print_72:0", shape=(2, 4), dtype=int32)
[[8 8 8 8]
 [8 8 8 8]]
------------
Tensor("Print_73:0", shape=(3, 3), dtype=int32)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
------------
Tensor("Print_74:0", shape=(2, 4), dtype=float32)
[[8. 8. 8. 8.]
 [8. 8. 8. 8.]]


### 2.其于其它变量的shape来创建常量

In [186]:
zeros = tf.zeros([2, 3])
show(tf.zeros_like(zeros))

ones = tf.ones([3, 3])
show(tf.ones_like(ones))

------------
Tensor("Print_75:0", shape=(2, 3), dtype=float32)
[[0. 0. 0.]
 [0. 0. 0.]]
------------
Tensor("Print_76:0", shape=(3, 3), dtype=float32)
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### 3.序列类常量

In [189]:
#使用样本个数，常用
linear_tsr = tf.linspace(start=0.0, stop=1, num=11)
show(linear_tsr)

#等价于linspace，但使用步长，有时不方便 
range_tsr = tf.range(0, 1, 0.1)
show(range_tsr)

------------
Tensor("Print_80:0", shape=(11,), dtype=float32)
[0.         0.1        0.2        0.3        0.4        0.5
 0.6        0.7        0.8        0.90000004 1.        ]
------------
Tensor("Print_81:0", shape=(10,), dtype=float32)
[0.         0.1        0.2        0.3        0.4        0.5
 0.6        0.70000005 0.8000001  0.9000001 ]


### 4.随机类常量

In [193]:
rand_unif_tsr = tf.random_uniform([2,3], 0, 10) #[0,10)的均匀分布
show(rand_unif_tsr)

randnorm = tf.random_normal([2,3], 0, 0.1) #均值0，标准差 0.1
show(randnorm)

trunc_norm = tf.truncated_normal([2,3], 0, 0.1) #同上，但2个标准差之外的截掉
show(trunc_norm)

value = tf.range(1,10)
show(value)

shuffle_output = tf.random_shuffle(value) #洗牌
show(shuffle_output)

rand_int_tsr = tf.random_uniform([3,4], 0, 100)
cropped_output = tf.random_crop(rand_int_tsr, [2,2])
show(rand_int_tsr)  #在3*4的矩阵上，随机取一个 2*2的子矩阵，常用于彩色图片 （高，宽，3颜色通道）
show(cropped_output)

------------
Tensor("Print_82:0", shape=(2, 3), dtype=float32)
[[8.281622  1.3080239 7.36483  ]
 [1.1540735 3.909098  5.1322756]]
------------
Tensor("Print_83:0", shape=(2, 3), dtype=float32)
[[-0.11423887 -0.04876159 -0.0490853 ]
 [ 0.12505543  0.03645957 -0.02149018]]
------------
Tensor("Print_84:0", shape=(2, 3), dtype=float32)
[[ 0.05192407 -0.0404477   0.02894362]
 [ 0.00758826 -0.0449824   0.05653958]]
------------
Tensor("Print_85:0", shape=(9,), dtype=int32)
[1 2 3 4 5 6 7 8 9]
------------
Tensor("Print_86:0", shape=(9,), dtype=int32)
[7 3 1 5 2 6 8 4 9]
------------
Tensor("Print_87:0", shape=(3, 4), dtype=float32)
[[84.8997    87.771454  62.022972  73.2254   ]
 [56.019447  93.32345   13.54661   26.176857 ]
 [31.59089    3.191197  62.688232   4.7851205]]
------------
Tensor("Print_88:0", shape=(2, 2), dtype=float32)
[[40.569614 36.05387 ]
 [22.989845 38.497223]]


### 创建变量tensor

In [202]:
cropped_output_var = tf.Variable(cropped_output)
show(cropped_output_var)


cropped_output_var2 = tf.Variable(tf.lin_space(7.0, 9, 3))

show(cropped_output_var2)


var1 = tf.Variable(tf.range(1,3))
var2 = tf.Variable(tf.range(4,8))
show(var1)
show(var2)


#转任意数组或常量到tensor
a = [1, 2, 3]
show(tf.convert_to_tensor(a))

------------
Tensor("Print_108:0", shape=(2, 2), dtype=float32)
[[77.92115  79.89994 ]
 [25.708044 71.838905]]
------------
Tensor("Print_109:0", shape=(3,), dtype=float32)
[7. 8. 9.]
------------
Tensor("Print_110:0", shape=(2,), dtype=int32)
[1 2]
------------
Tensor("Print_111:0", shape=(4,), dtype=int32)
[4 5 6 7]
------------
Tensor("Print_112:0", shape=(3,), dtype=int32)
[1 2 3]
