In [1]:
import torch

In [2]:
import numpy as np

### torch 基本处理单元

In [42]:
# 返回的数组大小5x4的矩阵
torch.Tensor(5, 4)


 1.8649  0.0000  0.0000  0.0000
 0.0000  0.0000  0.0000  0.0000
 0.0000  0.0000  0.0000  0.0000
 0.0000  0.0000  0.0000  0.0000
 0.0000  0.0000  0.0000  0.0000
[torch.FloatTensor of size 5x4]

In [4]:
# 返回的数组大小是5x4的矩阵，初始化是0~1的均匀分布
torch.rand(5, 4)


 0.8291  0.6567  0.0798  0.6863
 0.5554  0.4144  0.0306  0.9636
 0.8401  0.2958  0.7769  0.7632
 0.2375  0.4158  0.7268  0.0766
 0.3228  0.9441  0.2141  0.8944
[torch.FloatTensor of size 5x4]

In [5]:
# 得到矩阵大小
a = torch.rand(5, 4)
a.size()

torch.Size([5, 4])

In [6]:
# numpy 类似的返回5x4大小的矩阵
np.ones((5, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
# numpy 和 torch.Tensor 之间的转换
a = torch.rand(5, 4)
b = a.numpy()
print(b)

[[0.9369951  0.5596771  0.48438907 0.4550258 ]
 [0.85626704 0.20696163 0.09101939 0.03748655]
 [0.67770755 0.11567783 0.8768209  0.46507335]
 [0.7078351  0.6727687  0.64647424 0.5382129 ]
 [0.43035865 0.98845816 0.7456514  0.48348892]]


In [8]:
a = np.array([[3, 4], [3, 6]])
b = torch.from_numpy(a)
print(b)


 3  4
 3  6
[torch.LongTensor of size 2x2]



运算和numpy类似

In [9]:
x = torch.rand(5, 4)
y = torch.rand(5, 4)
c = 3

In [10]:
print(c * x)


 2.5313  2.7338  1.7323  0.9885
 0.6962  0.2229  0.8090  2.0777
 0.6350  1.0701  0.6429  2.6469
 0.7778  0.5461  1.4056  0.5576
 2.9672  2.7875  2.2046  1.2489
[torch.FloatTensor of size 5x4]



In [11]:
print(x + y)


 1.4573  1.0540  0.9641  0.7340
 1.1530  0.1058  0.5759  1.3669
 1.0711  1.0053  0.3605  1.2515
 1.1754  0.4045  0.5219  0.6195
 1.5196  1.6774  0.9453  0.7949
[torch.FloatTensor of size 5x4]



In [12]:
print(x.add(y))


 1.4573  1.0540  0.9641  0.7340
 1.1530  0.1058  0.5759  1.3669
 1.0711  1.0053  0.3605  1.2515
 1.1754  0.4045  0.5219  0.6195
 1.5196  1.6774  0.9453  0.7949
[torch.FloatTensor of size 5x4]



In [13]:
# 可以直接进行操作改变原对象，x+y或者x.add()并不会改变x，但是x.add_()则会对x进行改变
x.add_(y)


 1.4573  1.0540  0.9641  0.7340
 1.1530  0.1058  0.5759  1.3669
 1.0711  1.0053  0.3605  1.2515
 1.1754  0.4045  0.5219  0.6195
 1.5196  1.6774  0.9453  0.7949
[torch.FloatTensor of size 5x4]

In [14]:
print(x)


 1.4573  1.0540  0.9641  0.7340
 1.1530  0.1058  0.5759  1.3669
 1.0711  1.0053  0.3605  1.2515
 1.1754  0.4045  0.5219  0.6195
 1.5196  1.6774  0.9453  0.7949
[torch.FloatTensor of size 5x4]



将 torch.Tensor 放到 GPU 上

In [43]:
# 判断一下电脑是否支持GPU
torch.cuda.is_available()

True

In [44]:
a = torch.rand(5, 4)
a = a.cuda()
print(a)


 0.3591  0.8879  0.5967  0.7379
 0.0684  0.7664  0.9657  0.8231
 0.4758  0.6523  0.4394  0.3250
 0.1105  0.5620  0.1081  0.3409
 0.0851  0.0828  0.9969  0.3570
[torch.cuda.FloatTensor of size 5x4 (GPU 0)]



### torch 的自动求导功能
torch 和大部分框架一样有着自动求导功能，对象不再是 torch.Tensor，而是torch.autograd.Variable

本质上Variable和Tensor没有什么区别，不过Variable会放在一个计算图里面，可以进行前向传播和反向传播以及求导  

![1.png](http://upload-images.jianshu.io/upload_images/3623720-1c2694b72e0341ce.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

里面的creator表示通过什么操作得到的这个Variable，grad表示反向传播的梯度

In [17]:
from torch.autograd import Variable

In [18]:
# requires_grad 表示是否对其求梯度，默认是False
x = Variable(torch.Tensor([3]), requires_grad=True)
y = Variable(torch.Tensor([5]), requires_grad=True)
z = 2 * x + y + 4

In [19]:
# 对 x 和 y 分别求导
z.backward()

In [45]:
# x 的导数和 y 的导数
print('dz/dx: {}'.format(x.grad.data))
print('dz/dy: {}'.format(y.grad.data))

dz/dx: 
 2
[torch.FloatTensor of size 1]

dz/dy: 
 1
[torch.FloatTensor of size 1]



### 神经网络部分

所依赖的主要是 torch.nn 和 torch.nn.functional

torch.nn 里面有着所有的神经网络的层的操作，其用来构建网络，只有执行一次网络的运算才执行一次

torch.nn.functional 表示的是直接对其做一次向前运算操作

In [46]:
from torch import nn
import torch.nn.functional as F

In [47]:
# 基本的网络构建类模板
class net_name(nn.Module):
    def __init__(self):
        super(net_name, self).__init__()
        # 可以添加各种网络层
        self.conv1 = nn.Conv2d(3, 10, 3)
        # 具体每种层的参数可以去查看文档
        
    def forward(self, x):
        # 定义向前传播
        out = self.conv1(x)
        return out