### Numpy中的矩阵合并

列合并/扩展：np.column_stack()

行合并/扩展：np.row_stack()

In [1]:
import numpy as np

In [28]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [29]:
b = np.arange(10, 19).reshape(3, 3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [38]:
c = np.column_stack((a,b))
c

array([[ 0,  1,  2, 10, 11, 12],
       [ 3,  4,  5, 13, 14, 15],
       [ 6,  7,  8, 16, 17, 18]])