In [123]:
import time
import numpy as np


In [124]:
def g(x):
#     return x / (np.sum(np.exp(x)))
    return x / (np.sum(np.exp(x)))

In [358]:
np.random.seed(int(time.time()))
lay = 100
data = np.mat(np.random.randint(0,255,[lay,1]))
data.shape

(100, 1)

In [447]:

def elm_train(data,lay):
    np.random.seed(int(time.time()))
    W = np.mat(np.random.normal(size=(data.shape[1], lay)).astype('float64')) # (1 * 100)
    B = np.mat(np.random.normal(size=(data.shape[0], lay)).astype('float64')) # (1*100)
    temH = np.dot(data,W) + B
    H = temH
    H_1 = np.linalg.pinv(H)
    T = np.mat(np.ones((H_1.shape[1],1)).astype('float64') + 1)
    beita = np.dot(H_1,T)
    ##################test####################
    print("B.shape",B.shape)
    print("temH.shape",temH.shape)
    print("H.shape",H.shape)
    print("H_1.shape",H_1.shape)
    print("T.shape:",T.shape)
    ######################################
    return (temH, H, T, W, B, beita, T)


temH, H, T, W, B, beita, lable = elm_train(data,1000)
res = np.dot(H,beita)
T,res

B.shape (100, 1000)
temH.shape (100, 1000)
H.shape (100, 1000)
H_1.shape (1000, 100)
T.shape: (100, 1)


(matrix([[ 2.],
         [ 2.],
         [ 2.],
         [ 2.],
         [ 2.],
         [ 2.],
         [ 2.],
         [ 2.],
         [ 2.],
         [ 2.],
         [ 2.],
         [ 2.],
         [ 2.],
         [ 2.],
         [ 2.],
         [ 2.],
         [ 2.],
         [ 2.],
         [ 2.],
         [ 2.],
         [ 2.],
         [ 2.],
         [ 2.],
         [ 2.],
         [ 2.],
         [ 2.],
         [ 2.],
         [ 2.],
         [ 2.],
         [ 2.],
         [ 2.],
         [ 2.],
         [ 2.],
         [ 2.],
         [ 2.],
         [ 2.],
         [ 2.],
         [ 2.],
         [ 2.],
         [ 2.],
         [ 2.],
         [ 2.],
         [ 2.],
         [ 2.],
         [ 2.],
         [ 2.],
         [ 2.],
         [ 2.],
         [ 2.],
         [ 2.],
         [ 2.],
         [ 2.],
         [ 2.],
         [ 2.],
         [ 2.],
         [ 2.],
         [ 2.],
         [ 2.],
         [ 2.],
         [ 2.],
         [ 2.],
         [ 2.],
        

In [446]:
temH, H

(matrix([[  23.95867821,  273.32763963,  194.22030567, ...,  212.50784954,
           132.37056071,  209.86213191],
         [  14.03608655,  164.75072077,  116.82663912, ...,  129.48138918,
            78.97939661,  123.48896496],
         [  29.68869238,  318.27328868,  226.11556034, ...,  247.0797132 ,
           156.2414717 ,  241.7819436 ],
         ..., 
         [   4.04721044,   30.7384863 ,   20.48748223, ...,   23.80296519,
            15.07822321,   23.34726069],
         [  10.95577215,  109.49751758,   79.54970932, ...,   85.21050573,
            54.68836783,   84.57825106],
         [   5.92605978,   65.06510152,   45.31036677, ...,   51.10894775,
            32.44821966,   50.30127791]]),
 matrix([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
         [ 0.,  0.,  0., ...,  0.,  0.,  0.],
         [ 0.,  0.,  0., ...,  0.,  0.,  0.],
         ..., 
         [ 0.,  0.,  0., ...,  0.,  0.,  0.],
         [ 0.,  0.,  0., ...,  0.,  0.,  0.],
         [ 0.,  0.,  0., ...,  0.,  0.,  0

In [432]:
data1 = np.mat(np.random.randint(0,255,[lay,1]))

In [433]:
data[12] = 100
def elm_test(data,W,B,beita,lable):
    temH = np.dot(data, W) + B
    H = g(temH)
    TT = np.dot(H,beita)
    Res = lable - TT
    ################Test#################
    print("TT.shape",TT.shape)
    print("lable.shape:",lable.shape)
    print("Res.shape:",Res.shape)
    #################################
    return np.cov(Res.T)

print(elm_test(data,W,B,beita,lable))
print(elm_test(data1,W,B,beita,lable))

TT.shape (100, 1)
lable.shape: (100, 1)
Res.shape: (100, 1)
0.0
TT.shape (100, 1)
lable.shape: (100, 1)
Res.shape: (100, 1)
0.0


C:\Users\Albert\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: overflow encountered in exp
  


In [120]:
# 画图
from PIL import Image

In [122]:
img = Image.fromarray(data)
img.show()